[package]
name = "songset"
version = "0.1.0"
authors = ["Peter Simonyi <pts@petersimonyi.ca>"]
build = "build.rs"

[build-dependencies]
peg = "0.5"

[dependencies]
pango = "0.3.0"

[dependencies.gtk]
version = "0.3.0"
features = ["v3_22"]
